[package]
name = "ConfigChecker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
config = "0.13.1"
regex = "1.8.1"
winapi = "0.3.9"
